export const actions = {
  blog: {
    DATA_FETCHING: "BLOG_DATA_FETCHING",
    DATA_FETCHED: "BLOG_DATA_FETCHED",
    DATA_FETCHED_ERROR: "BLOG_DATA_FETCHED_ERROR",
  },
  singleblog: {
    DATA_FETCHING: "SINGLE_BLOG_DATA_FETCHING",
    DATA_FETCHED: "SINGLE_BLOG_DATA_FETCHED",
    DATA_FETCHED_ERROR: "SINGLE_BLOG_DATA_FETCHED_ERROR",
  },

  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
    IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
  },
};
